# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "xhci_pci_renesas" "usb_storage" "usbhid" "sd_mod" "md_mod" "raid1" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "it87" ];
  boot.extraModulePackages = [ ];
  boot.swraid.enable = true;
  boot.swraid.mdadmConf = ''
    ARRAY /dev/md0 metadata=1.2 name=md0 UUID=2c1b1455-6ab2-1c68-e861-9facaa808236
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/aef2b228-80ab-4a58-bb04-376db4ae7256";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/380b0f76-9f65-4a26-92a2-7001a67034ca";
      fsType = "ext4";
    };

  fileSystems."/data" = {
    device = "/dev/md0";
    fsType = "ext4";
    options = [ "noatime" "defaults" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
