{ config, ... }:
{
  hardware.fancontrol.enable = true;
  hardware.fancontrol.config = ''
    # Configuration file generated by pwmconfig
    INTERVAL=10
    DEVPATH=
    DEVNAME=
    FCTEMPS=/sys/class/hwmon/hwmon0/pwm1=/sys/class/hwmon/hwmon0/temp3_input /sys/class/hwmon/hwmon0/pwm2=/sys/class/hwmon/hwmon0/temp3_input
    FCFANS=/sys/class/hwmon/hwmon0/pwm1=/sys/class/hwmon/hwmon0/fan1_input /sys/class/hwmon/hwmon0/pwm2=/sys/class/hwmon/hwmon0/fan2_input
    MINTEMP=/sys/class/hwmon/hwmon0/pwm1=25 /sys/class/hwmon/hwmon0/pwm2=25
    MAXTEMP=/sys/class/hwmon/hwmon0/pwm1=60 /sys/class/hwmon/hwmon0/pwm2=60
    MINSTART=/sys/class/hwmon/hwmon0/pwm1=150 /sys/class/hwmon/hwmon0/pwm2=150
    MINSTOP=/sys/class/hwmon/hwmon0/pwm1=100 /sys/class/hwmon/hwmon0/pwm2=100
  '';
}
